//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICTURE
    {
        public int ID_PICTURE { get; set; }
        public int ID_CATEGORY_PICTURE { get; set; }
        public string NAME_PICTURE { get; set; }
        public System.DateTime DATE_PUBLISH_PICTURE { get; set; }
        public System.DateTime DATE_UPLOAD_PICTURE { get; set; }
        public decimal PRICE_PICTURE { get; set; }
    }
}
